// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeeSharpersCinema.Models.Database;

namespace SeeSharpersCinema.Data.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20210315095459_ReservedSeats")]
    partial class ReservedSeats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeeSharpersCinema.Models.Film.Movie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewIndication")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Roger Michell",
                            Duration = 98,
                            Genre = 6,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/32660_128633_ps_sd-high.jpg",
                            Technique = "2D",
                            Title = "Blackbird",
                            ViewIndication = 5,
                            Year = 2021
                        },
                        new
                        {
                            Id = 2L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Kar-Wai Wong",
                            Duration = 98,
                            Genre = 6,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/33783_134425_ps_sd-high.jpg",
                            Technique = "2D",
                            Title = "In the mood for love",
                            ViewIndication = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3L,
                            Country = "NL",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Matthijs van Heijningen Jr.",
                            Duration = 124,
                            Genre = 6,
                            Language = "Nederlands",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/PathePartners/movie-25169-SlagOmDeScheldeDe_Poster_DEF.jpg",
                            Technique = "2D",
                            Title = "De slag om de schelde",
                            ViewIndication = 5,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Kar-Wai Wong",
                            Duration = 84,
                            Genre = 10,
                            Language = "Nederlands",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/23672_133688_ps_sd-high.jpg",
                            Technique = "3D",
                            Title = "Ainbo: Heldin van de amazone",
                            ViewIndication = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 5L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Spike Lee",
                            Duration = 105,
                            Genre = 16,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508//gfx_content/other/api/filmdepot/v1/movie/download/33816_134505_ps_sd-high.jpg",
                            Technique = "2D",
                            Title = "David Byrne's amerikan utopia",
                            ViewIndication = 0,
                            Year = 2021
                        },
                        new
                        {
                            Id = 6L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Lee Daniels",
                            Duration = 130,
                            Genre = 6,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/33645_134768_ps_sd-high.jpg",
                            Technique = "2D",
                            Title = "The united stats vs. billie holiday",
                            ViewIndication = 4,
                            Year = 2021
                        },
                        new
                        {
                            Id = 7L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Joel Crawford",
                            Duration = 95,
                            Genre = 9,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/23557_133608_ps_sd-high.jpg",
                            Technique = "3D",
                            Title = "The croods: a new age (OV)",
                            ViewIndication = 1,
                            Year = 2020
                        },
                        new
                        {
                            Id = 8L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Joel Crawford",
                            Duration = 95,
                            Genre = 10,
                            Language = "Nederlands",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/23557_133608_ps_sd-high.jpg",
                            Technique = "3D",
                            Title = "De croods 2: een nieuw begin (NL)",
                            ViewIndication = 1,
                            Year = 2020
                        },
                        new
                        {
                            Id = 9L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Charlène Favier",
                            Duration = 92,
                            Genre = 6,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/Slalom.jpg",
                            Technique = "2D",
                            Title = "Slalom",
                            ViewIndication = 2,
                            Year = 2020
                        },
                        new
                        {
                            Id = 10L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Donato Carrisi",
                            Duration = 130,
                            Genre = 8,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/33764_133801_ps_sd-high.jpg",
                            Technique = "2D",
                            Title = "Into the labyrinth",
                            ViewIndication = 2,
                            Year = 2021
                        },
                        new
                        {
                            Id = 11L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Mike P. Nelson",
                            Duration = 110,
                            Genre = 2,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/33804_134756_ps_sd-high.jpg",
                            Technique = "2D",
                            Title = "Wrong turn",
                            ViewIndication = 5,
                            Year = 2020
                        },
                        new
                        {
                            Id = 12L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "David Silverman",
                            Duration = 84,
                            Genre = 10,
                            Language = "Nederlands",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/33774_133282_ps_sd-high.jpg",
                            Technique = "2D",
                            Title = "De Flummels",
                            ViewIndication = 1,
                            Year = 2021
                        },
                        new
                        {
                            Id = 13L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Ilya Naishuller",
                            Duration = 92,
                            Genre = 5,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/23923_133307_ps_sd-high.jpg",
                            Technique = "2D",
                            Title = "Nobody",
                            ViewIndication = 5,
                            Year = 2021
                        },
                        new
                        {
                            Id = 14L,
                            Country = "USA",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum rutrum magna at sagittis. Curabitur viverra hendrerit enim, at gravida elit venenatis vel. Pellentesque aliquam maximus suscipit. Pellentesque et dolor elit. Duis rhoncus interdum quam, maximus pharetra tortor auctor sed. Ut congue molestie nisl ut aliquam.",
                            Director = "Florian Zeller",
                            Duration = 97,
                            Genre = 6,
                            Language = "Original",
                            PosterUrl = "https://media.pathe.nl/thumb/360x508/gfx_content/other/api/filmdepot/v1/movie/download/33495_134471_ps_sd-high.jpg",
                            Technique = "2D",
                            Title = "The Father",
                            ViewIndication = 2,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("SeeSharpersCinema.Models.Program.PlayList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.Property<long>("TimeSlotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("PlayList");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MovieId = 1L,
                            TimeSlotId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            MovieId = 2L,
                            TimeSlotId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            MovieId = 3L,
                            TimeSlotId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            MovieId = 4L,
                            TimeSlotId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            MovieId = 5L,
                            TimeSlotId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            MovieId = 6L,
                            TimeSlotId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            MovieId = 7L,
                            TimeSlotId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            MovieId = 8L,
                            TimeSlotId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            MovieId = 9L,
                            TimeSlotId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            MovieId = 10L,
                            TimeSlotId = 10L
                        },
                        new
                        {
                            Id = 11L,
                            MovieId = 11L,
                            TimeSlotId = 11L
                        },
                        new
                        {
                            Id = 12L,
                            MovieId = 12L,
                            TimeSlotId = 12L
                        },
                        new
                        {
                            Id = 13L,
                            MovieId = 13L,
                            TimeSlotId = 13L
                        },
                        new
                        {
                            Id = 14L,
                            MovieId = 14L,
                            TimeSlotId = 14L
                        },
                        new
                        {
                            Id = 15L,
                            MovieId = 1L,
                            TimeSlotId = 15L
                        },
                        new
                        {
                            Id = 16L,
                            MovieId = 2L,
                            TimeSlotId = 16L
                        },
                        new
                        {
                            Id = 17L,
                            MovieId = 3L,
                            TimeSlotId = 17L
                        },
                        new
                        {
                            Id = 18L,
                            MovieId = 4L,
                            TimeSlotId = 18L
                        },
                        new
                        {
                            Id = 19L,
                            MovieId = 5L,
                            TimeSlotId = 19L
                        },
                        new
                        {
                            Id = 20L,
                            MovieId = 6L,
                            TimeSlotId = 20L
                        },
                        new
                        {
                            Id = 21L,
                            MovieId = 7L,
                            TimeSlotId = 21L
                        },
                        new
                        {
                            Id = 22L,
                            MovieId = 8L,
                            TimeSlotId = 22L
                        },
                        new
                        {
                            Id = 23L,
                            MovieId = 9L,
                            TimeSlotId = 23L
                        },
                        new
                        {
                            Id = 24L,
                            MovieId = 10L,
                            TimeSlotId = 24L
                        },
                        new
                        {
                            Id = 25L,
                            MovieId = 11L,
                            TimeSlotId = 25L
                        },
                        new
                        {
                            Id = 26L,
                            MovieId = 12L,
                            TimeSlotId = 26L
                        },
                        new
                        {
                            Id = 27L,
                            MovieId = 13L,
                            TimeSlotId = 27L
                        },
                        new
                        {
                            Id = 28L,
                            MovieId = 14L,
                            TimeSlotId = 28L
                        },
                        new
                        {
                            Id = 29L,
                            MovieId = 1L,
                            TimeSlotId = 29L
                        },
                        new
                        {
                            Id = 30L,
                            MovieId = 2L,
                            TimeSlotId = 30L
                        },
                        new
                        {
                            Id = 31L,
                            MovieId = 3L,
                            TimeSlotId = 31L
                        },
                        new
                        {
                            Id = 32L,
                            MovieId = 4L,
                            TimeSlotId = 32L
                        },
                        new
                        {
                            Id = 33L,
                            MovieId = 5L,
                            TimeSlotId = 33L
                        },
                        new
                        {
                            Id = 34L,
                            MovieId = 6L,
                            TimeSlotId = 34L
                        },
                        new
                        {
                            Id = 35L,
                            MovieId = 7L,
                            TimeSlotId = 35L
                        },
                        new
                        {
                            Id = 36L,
                            MovieId = 8L,
                            TimeSlotId = 36L
                        },
                        new
                        {
                            Id = 37L,
                            MovieId = 9L,
                            TimeSlotId = 37L
                        },
                        new
                        {
                            Id = 38L,
                            MovieId = 10L,
                            TimeSlotId = 38L
                        },
                        new
                        {
                            Id = 39L,
                            MovieId = 11L,
                            TimeSlotId = 39L
                        },
                        new
                        {
                            Id = 40L,
                            MovieId = 12L,
                            TimeSlotId = 40L
                        },
                        new
                        {
                            Id = 41L,
                            MovieId = 13L,
                            TimeSlotId = 41L
                        },
                        new
                        {
                            Id = 42L,
                            MovieId = 14L,
                            TimeSlotId = 42L
                        },
                        new
                        {
                            Id = 43L,
                            MovieId = 1L,
                            TimeSlotId = 43L
                        },
                        new
                        {
                            Id = 44L,
                            MovieId = 2L,
                            TimeSlotId = 44L
                        },
                        new
                        {
                            Id = 45L,
                            MovieId = 3L,
                            TimeSlotId = 45L
                        },
                        new
                        {
                            Id = 46L,
                            MovieId = 4L,
                            TimeSlotId = 46L
                        },
                        new
                        {
                            Id = 47L,
                            MovieId = 5L,
                            TimeSlotId = 47L
                        },
                        new
                        {
                            Id = 48L,
                            MovieId = 6L,
                            TimeSlotId = 48L
                        },
                        new
                        {
                            Id = 49L,
                            MovieId = 7L,
                            TimeSlotId = 49L
                        },
                        new
                        {
                            Id = 50L,
                            MovieId = 8L,
                            TimeSlotId = 50L
                        },
                        new
                        {
                            Id = 51L,
                            MovieId = 9L,
                            TimeSlotId = 51L
                        },
                        new
                        {
                            Id = 52L,
                            MovieId = 10L,
                            TimeSlotId = 52L
                        },
                        new
                        {
                            Id = 53L,
                            MovieId = 11L,
                            TimeSlotId = 53L
                        },
                        new
                        {
                            Id = 54L,
                            MovieId = 12L,
                            TimeSlotId = 54L
                        },
                        new
                        {
                            Id = 55L,
                            MovieId = 13L,
                            TimeSlotId = 55L
                        },
                        new
                        {
                            Id = 56L,
                            MovieId = 14L,
                            TimeSlotId = 56L
                        });
                });

            modelBuilder.Entity("SeeSharpersCinema.Models.Theater.Cinema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cinema");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Gedempte Zuiderdiep 78",
                            City = "Groningen",
                            Name = "Pathé",
                            Phone = "0885152050",
                            TotalCapacity = 1500,
                            TotalRooms = 5
                        });
                });

            modelBuilder.Entity("SeeSharpersCinema.Models.Theater.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<long>("CinemaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Capacity = 300,
                            CinemaId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Capacity = 300,
                            CinemaId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Capacity = 300,
                            CinemaId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Capacity = 300,
                            CinemaId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Capacity = 300,
                            CinemaId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Capacity = 300,
                            CinemaId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Capacity = 300,
                            CinemaId = 1L
                        });
                });

            modelBuilder.Entity("SeeSharpersCinema.Models.TimeSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SlotEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SlotStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("TimeSlot");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            RoomId = 1L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 2L,
                            RoomId = 1L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 3L,
                            RoomId = 2L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 4L,
                            RoomId = 2L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 5L,
                            RoomId = 3L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 6L,
                            RoomId = 3L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 7L,
                            RoomId = 4L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 8L,
                            RoomId = 4L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 9L,
                            RoomId = 5L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 10L,
                            RoomId = 5L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 11L,
                            RoomId = 6L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 12L,
                            RoomId = 6L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 13L,
                            RoomId = 7L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 14L,
                            RoomId = 7L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 9, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 15L,
                            RoomId = 1L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 16L,
                            RoomId = 1L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 10, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 17L,
                            RoomId = 2L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 18L,
                            RoomId = 2L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 10, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 9
                        },
                        new
                        {
                            Id = 19L,
                            RoomId = 3L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 20L,
                            RoomId = 3L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 21L,
                            RoomId = 4L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 22L,
                            RoomId = 4L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 23L,
                            RoomId = 5L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 24L,
                            RoomId = 5L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 25L,
                            RoomId = 6L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 26L,
                            RoomId = 6L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 27L,
                            RoomId = 7L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 12, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 28L,
                            RoomId = 7L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 29L,
                            RoomId = 1L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 13, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 30L,
                            RoomId = 1L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 13, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 31L,
                            RoomId = 2L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 13, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 32L,
                            RoomId = 2L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 33L,
                            RoomId = 3L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 14, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 34L,
                            RoomId = 3L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 35L,
                            RoomId = 4L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 36L,
                            RoomId = 4L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 15, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 37L,
                            RoomId = 5L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 38L,
                            RoomId = 5L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 39L,
                            RoomId = 6L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 16, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 40L,
                            RoomId = 6L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 41L,
                            RoomId = 7L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 17, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 42L,
                            RoomId = 7L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 17, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 43L,
                            RoomId = 1L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 17, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 10
                        },
                        new
                        {
                            Id = 44L,
                            RoomId = 1L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 18, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 45L,
                            RoomId = 2L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 46L,
                            RoomId = 2L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 18, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 47L,
                            RoomId = 3L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 48L,
                            RoomId = 3L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 18, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 49L,
                            RoomId = 4L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 19, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 50L,
                            RoomId = 4L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 19, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 51L,
                            RoomId = 5L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 19, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 52L,
                            RoomId = 5L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 53L,
                            RoomId = 6L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 54L,
                            RoomId = 6L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 55L,
                            RoomId = 7L,
                            SlotEnd = new DateTime(2021, 3, 9, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 21, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        },
                        new
                        {
                            Id = 56L,
                            RoomId = 7L,
                            SlotEnd = new DateTime(2021, 3, 9, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            SlotStart = new DateTime(2021, 3, 21, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Week = 11
                        });
                });

            modelBuilder.Entity("SeeSharpersCinema.Models.Program.PlayList", b =>
                {
                    b.HasOne("SeeSharpersCinema.Models.Film.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeeSharpersCinema.Models.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("SeeSharpersCinema.Models.Theater.Room", b =>
                {
                    b.HasOne("SeeSharpersCinema.Models.Theater.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("SeeSharpersCinema.Models.TimeSlot", b =>
                {
                    b.HasOne("SeeSharpersCinema.Models.Theater.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
